[package]
name = "badchat"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5.13"
failure = "0.1.2"
log = "0.4.5"
mio = "0.6.16"
rustls = "0.14.0"
vecio = "0.1.0"
