[package]
name = "badchat"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
cast = "0.2.2"
dns-lookup = "1.0.0"
env_logger = "0.8"
failure = "0.1.3"
log = "0.4.6"
maplit = "1"
mio = "0.6"
pbkdf2 = "0.6"
rand = "0.8"
rustls = "0.17"
vecio = "0.1.0"

[dependencies.rusqlite]
version = "0.25"
features = ["bundled"]
