keys:
    openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 \
      -nodes -keyout localhost-self-signed.key -out localhost-self-signed.crt -subj "/CN=localhost" \
      -addext "subjectAltName=DNS:localhost"     
